name: CI
on: [push, pull_request, workflow_dispatch]

env:
  VITE_APP_API_KEY: secret.API_KEY
  VITE_APP_API_URL: secret.API_URL
  VITE_APP_AUTH_DOMAIN: secret.AUTH_DOMAIN
  VITE_APP_DATABASE_URL: secret.DATABASE_URL
  VITE_APP_PROJECT_ID: secret.PROJECT_ID
  VITE_APP_STORAGE_BUCKET: secret.STORAGE_BUCKET
  VITE_APP_MESSAGING_SENDER_ID: secret.MESSAGING_SENDER_ID
  VITE_APP_APP_ID: secret.APP_ID
  VITE_APP_MEASUREMENT_ID: secret.MEASUREMENT_ID

jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Connect to github npm
        run: |
          echo '${{ secrets.CONFIG_GITHUB_NPM }}' > ~/.npmrc

      - run: npm install --legacy-peer-deps

      - name: Cypress dependencies
        # From: https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements, Ubuntu section
        run: |
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Component testing
        run: npm run test:component

      - name: E2E testing
        run: npm run test:e2e

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - run: npm install --location=global prettier
      - run: prettier --check "src/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"
